"""empty message

Revision ID: 0283c6b1c9c1
Revises: f9be5d4ebdd8
Create Date: 2023-01-22 21:42:42.084573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0283c6b1c9c1'
down_revision = 'f9be5d4ebdd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('accounting_period',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('accounting_period',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)

    # ### end Alembic commands ###
