"""empty message

Revision ID: 260a326b939d
Revises: a710019f0145
Create Date: 2023-01-22 21:04:54.776651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260a326b939d'
down_revision = 'a710019f0145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accounting_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accounting_period', sa.Integer(), nullable=True))

    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accounting_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accounting_period', sa.Integer(), nullable=True))

    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accounting_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accounting_period', sa.Integer(), nullable=True))

    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accounting_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accounting_period', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.drop_column('accounting_period')
        batch_op.drop_column('accounting_year')

    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.drop_column('accounting_period')
        batch_op.drop_column('accounting_year')

    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.drop_column('accounting_period')
        batch_op.drop_column('accounting_year')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('accounting_period')
        batch_op.drop_column('accounting_year')

    # ### end Alembic commands ###
