"""empty message

Revision ID: 49065468388a
Revises: ba989c450a28
Create Date: 2023-01-26 21:19:42.197303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49065468388a'
down_revision = 'ba989c450a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('journal_number', sa.Integer(), nullable=True))

    with op.batch_alter_table('nominal_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('client_code', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('transaction_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('net_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vat_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reference', sa.String(length=50), nullable=True))
        batch_op.drop_column('journal_date')
        batch_op.drop_column('journal_description')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=1),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.String(length=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    with op.batch_alter_table('nominal_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('journal_description', sa.VARCHAR(length=40), nullable=True))
        batch_op.add_column(sa.Column('journal_date', sa.VARCHAR(length=40), nullable=True))
        batch_op.drop_column('reference')
        batch_op.drop_column('total_value')
        batch_op.drop_column('vat_value')
        batch_op.drop_column('net_value')
        batch_op.drop_column('date')
        batch_op.drop_column('transaction_number')
        batch_op.drop_column('client_code')
        batch_op.drop_column('transaction_type')

    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.drop_column('journal_number')

    # ### end Alembic commands ###
