"""empty message

Revision ID: 76e762613180
Revises: a999aa2a8ae7
Create Date: 2023-01-14 22:07:56.916620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e762613180'
down_revision = 'a999aa2a8ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_of_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))

    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_code', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('invoice_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('nominal_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('net_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vat_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('date_posted', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('user_posted', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.drop_column('user_posted')
        batch_op.drop_column('date_posted')
        batch_op.drop_column('total_value')
        batch_op.drop_column('vat_value')
        batch_op.drop_column('net_value')
        batch_op.drop_column('nominal_code')
        batch_op.drop_column('invoice_date')
        batch_op.drop_column('customer_code')

    with op.batch_alter_table('chart_of_accounts', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
