"""empty message

Revision ID: 9d154e35f032
Revises: e6fa00cf9690
Create Date: 2023-01-17 21:17:39.971428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d154e35f032'
down_revision = 'e6fa00cf9690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('journal_date', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('journal_description', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.drop_column('journal_description')
        batch_op.drop_column('journal_date')

    # ### end Alembic commands ###
