"""empty message

Revision ID: a710019f0145
Revises: 9d154e35f032
Create Date: 2023-01-21 18:15:28.400249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a710019f0145'
down_revision = '9d154e35f032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted_by', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('posted_on', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.drop_column('posted_on')
        batch_op.drop_column('posted_by')

    # ### end Alembic commands ###
