"""empty message

Revision ID: a999aa2a8ae7
Revises: 
Create Date: 2023-01-14 16:16:03.583207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a999aa2a8ae7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('customer_name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('customer_code', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('customer_code')
        batch_op.drop_column('customer_name')
        batch_op.drop_column('company')

    # ### end Alembic commands ###
