"""empty message

Revision ID: ba989c450a28
Revises: 0283c6b1c9c1
Create Date: 2023-01-22 21:43:03.693831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba989c450a28'
down_revision = '0283c6b1c9c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('accounting_period',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('accounting_period',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
