"""empty message

Revision ID: f9be5d4ebdd8
Revises: 260a326b939d
Create Date: 2023-01-22 21:37:39.530747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9be5d4ebdd8'
down_revision = '260a326b939d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('accounting_year',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=True)
        batch_op.alter_column('accounting_period',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=True)

    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.alter_column('accounting_year',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=True)
        batch_op.alter_column('accounting_period',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=True)

    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.alter_column('accounting_year',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=True)
        batch_op.alter_column('accounting_period',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=True)

    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.alter_column('accounting_year',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=True)
        batch_op.alter_column('accounting_period',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.alter_column('accounting_period',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('accounting_year',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.alter_column('accounting_period',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('accounting_year',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.alter_column('accounting_period',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('accounting_year',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('accounting_period',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('accounting_year',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
