name: pythonanywhere-deployment
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
